exec Create_item_accessory 'Hospitalize Care';
exec Create_item_accessory 'Usuperfla';
exec Create_item_accessory 'Ops Stick';
exec Create_item_accessory 'JC Rist';
exec Create_item_accessory 'Ferry Ride';
exec Create_item_accessory 'MRJ BooGie';
exec Create_item_accessory 'ZGas';
exec Create_item_accessory 'Kronet';
exec Create_item_accessory 'Cali Jente';
exec Create_item_accessory 'ZUnkillable';
exec Create_item_accessory 'Walterror Parisley';
exec Create_item_accessory 'Devlana';
exec Create_item_accessory 'Walter Paisley';
exec Create_item_accessory 'Sicks Spades';
exec Create_item_accessory 'DaCup InHand';
exec Create_item_accessory 'PsyBrrWar';
exec Create_item_accessory 'Refer Skillet';
exec Create_item_accessory 'XZBtChion';
exec Create_item_accessory 'Mink Herr';
exec Create_item_accessory 'ImNnJl';
exec Create_item_accessory 'Icy Gif';
exec Create_item_accessory 'Water Rush';
exec Create_item_accessory 'CharleneOld';
exec Create_item_accessory 'Strickn ENT';
exec Create_item_accessory 'Andrew Stiagmata';
exec Create_item_accessory 'JuicyRSE';
exec Create_item_accessory 'Ops Stick';
exec Create_item_accessory 'JC Rist';
exec Create_item_accessory 'Ferry Ride';
exec Create_item_accessory 'Slim Orange Aura';
exec Create_item_accessory 'Blue Aura';
exec Create_item_accessory 'Green Aura';
exec Create_item_accessory 'Purple Aura';
